### ISSUE TITLE
Release a new version on the forge

### ISSUE THREAD

**Issue by edestecd** [justicel/puppet-phpmyadmin#40]
@justicel can you release a new version on the forge...

**Comment by justicel** [comment]
I will indeed! Give me a day or two as I just got back from a vacation. Want to check over the current module status in general.

**Comment by edestecd** [comment]
@justicel ping

**Comment by justicel** [comment]
I added a calendar entry to do it tomorrow. I feel ashamed :P

**Comment by justicel** [comment]
As promised! https://forge.puppetlabs.com/jlondon/phpmyadmin/readme

**Comment by edestecd** [comment]
Awesome... I look forward to removing those git lines from my Puppetfile :)
