### ISSUE TITLE
Blowfish path does not work on RedHat

### ISSUE THREAD

**Issue by edestecd** [justicel/puppet-phpmyadmin#41]
https://github.com/justicel/puppet-phpmyadmin/blob/master/manifests/server.pp#L55
This path is hardcoded for Debian only.
After pr #36, it now crashes on RedHat

**Comment by justicel** [comment]
Ack. I'll fix that. Thanks for the report.

**Comment by edestecd** [comment]
I've almost got a PR ready... :)

**Comment by justicel** [comment]
Okay, great :). Looking at the original PR (I should have examined it more closely), also will need to fix for the www-data user and pull that from the $::apache params.

**Comment by edestecd** [comment]
Great, the new version works great on RedHat :+1:
