### ISSUE TITLE
ip address '/' appears to be invalid: The specified IP address is invalid.

### ISSUE THREAD

**Issue by NotoriousBig** [justicel/puppet-phpmyadmin#44]
Hello, 

On a fresh new install (centos 7, latest puppetlabs/apache), the phpmyadmin won't start because of a syntax error in phpMyAdmin.conf.

in phpMyAdmin.conf.erb, <%= range %> was replaces by '/'. I just don't know how to fix it

Bye

**Comment by fgerards** [comment]
+1 - the sample config is somewhat confusing to me --- where does ${::ipaddress} come from ?
I also got the error described above

**Comment by wmoore28** [comment]
Old post, but maybe this is useful...

I had same issue out of the box on RHEL7.  Issue was $ip_access_ranges defaults to ${::network_eth0}/${::network_eth0}.  On 7, it's em1 (run ifconfig) to find out for sure.  So facter returns "" for each of those variables, giving you "/".  So just set ip_access_ranges when initializing.
