### ISSUE TITLE
purge exported resource

### ISSUE THREAD

**Issue by jfgibbins** [justicel/puppet-phpmyadmin#48]
While I love the @@ export feature to dynamically add hosts, can you please add something to allow dynamic deletion as well when databases are retired

**Comment by justicel** [comment]
This is not really a function of the module. When a resource is cleaned up in the DB it should no longer be exported by Puppet and will thus not be added to the configs when they are built.

**Comment by jfgibbins** [comment]
Not sure if it was something I had done while using, but they weren't disappearing over time. I was doing some modification to allow the entire manifest to be done in hiera including as profile includes, but it does as you say now, hence why I closed it.  So yeah!!, did my first forking of a project, lol.  Also, did another fork to create the phppgadmin version of your script, also with the additional features.  Appreciate the module you made.  I'm going to use the export function I learned from your code on quite a few other things now.
